
CREATE TABLE daily_reports (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  report_date DATE NOT NULL UNIQUE,
  total_focus_time INTEGER NOT NULL DEFAULT 0,
  completed_cycles INTEGER NOT NULL DEFAULT 0,
  interrupted_cycles INTEGER NOT NULL DEFAULT 0,
  report_content TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
