CREATE TABLE user_settings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL UNIQUE,
  focus_time INTEGER DEFAULT 25,
  short_break_time INTEGER DEFAULT 5,
  long_break_time INTEGER DEFAULT 15,
  auto_start_breaks BOOLEAN DEFAULT 0,
  auto_start_pomodoros BOOLEAN DEFAULT 0,
  sound_enabled BOOLEAN DEFAULT 1,
  notifications_enabled BOOLEAN DEFAULT 1,
  auto_commit BOOLEAN DEFAULT 0,
  auto_push BOOLEAN DEFAULT 0,
  git_commit_template TEXT DEFAULT 'feat: {cycle_name} ({duration}min)',
  theme TEXT DEFAULT 'dark',
  accent_color TEXT DEFAULT '#3B82F6',
  notification_sound TEXT DEFAULT 'default',
  notification_volume INTEGER DEFAULT 50,
  auto_generate_reports BOOLEAN DEFAULT 1,
  report_format TEXT DEFAULT 'txt',
  oauth_preferences TEXT DEFAULT '{}',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
); 